module:
  hugoVersion:
    min: "0.69.0"
  mounts:
  - source: assets
    target: assets/tnd-styles
  - source: partials
    target: layouts/partials/tnd-styles
  - source: console
    target: layouts/partials/tnd-styles
  imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-tags